### ISSUE TITLE
[BUG] Fly False Positive

### ISSUE THREAD

**Issue by Slawman07** [JasonHorkles/Silverstone#11]
#### Server this occurred in (in the player tab list):

~~Silverstone Survival~~ [Main]
#### World this occurred in (in the player tab list):

~~?~~ [main]
#### The coordinates at/near the glitch (if applicable):

~~?~~ [N/A]
#### My Minecraft username:

Slawman07
#### What I was doing when the glitch occurred:

Making a bubble elevator
#### What happened:

Got kicked
#### What was supposed to happen:

successfully swim up

**Comment by JasonHorkles** [comment]
Please provide evidence of this happening

**Comment by JasonHorkles** [comment]
[Video](https://1drv.ms/v/s!ArOS099NaR9LiIAUqwPwK9r4w1ueDw?e=ESlX9t)

**Comment by JasonHorkles** [comment]
The issue has been reported to the anti-cheat plugin [here](https://github.com/jiangdashao/Matrix-Issues/issues/1834)
I'll close the issue once it's been fixed.
