### ISSUE TITLE
[STAFF] Slawman07

### ISSUE THREAD

**Issue by Slawman07** [JasonHorkles/Silverstone#12]
#### Am I re-submitting my application?
No

#### My Discord username and tag:
Slawman07#0821

#### My Minecraft username:
Slawman07

#### My current rank (shown in tab):
Nothing

#### My current time played on the server:
26 Hours

#### My current age (if you don't want this to be public DM it to me on Discord):
I sent you a friend request

#### Why I want to be a staff member:
Because I really like this server, and want to make it the best it can be!

#### How often am I / will I be on the server?
All the time.

#### On a scale of 1-10, how good of a staff member do I think I'd be (1 being terrible and 10 being fantastic)?
10

#### Do I feel like I'm worthy of being a staff member?
Yes.

#### Do I swear I'll do my best to enforce the server rules at all times?
Yes, I am very honest and minding person.

**Comment by Slawman07** [comment]
For some reason its not showing my answers

**Comment by JasonHorkles** [comment]
Sorry, but your request has been declined for being under the age limits for both GitHub and Discord.
