### ISSUE TITLE
[STAFF] Hydromoon

### ISSUE THREAD

**Issue by Hydromoon4493** [JasonHorkles/Silverstone#14]
#### Am I re-submitting my application?

No
#### My Discord username and tag:

Hydromoon#0023
#### My Minecraft username:

Hydromoon
#### My current rank (shown in tab):

Default Player
#### My current time played on the server:

24 Hours
#### My current age (if you don't want this to be public DM it to me on Discord):

Messaged in DM
#### Why I want to be a staff member:

I've never been stafff beofre and want to try it and i want to help make this server a better place for players.
#### How often am I / will I be on the server?

Very often
#### On a scale of 1-10, how good of a staff member do I think I'd be (1 being terrible and 10 being fantastic)?

9
#### Do I feel like I'm worthy of being a staff member?

Because I am helpful and trustworthy and will enforce the rules
#### Do I swear I'll do my best to enforce the server rules at all times?

Yes!

**Comment by Hydromoon4493** [comment]
I'm ok with that I just would like to know why?

**Comment by JasonHorkles** [comment]
The staff felt that based off your actions we should not accept the application

**Comment by JasonHorkles** [comment]
Because of lying, you will no longer be able to re-submit staff applications.
