### ISSUE TITLE
[BUG] When I went down one level in spleef, it said the opponent won.

### ISSUE THREAD

**Issue by n0TaN00b473** [JasonHorkles/Silverstone#20]
#### Server this occurred in (in the player tab list):
Silverstone survival

#### World this occurred in (in the player tab list):
Normal world?

#### The coordinates at/near the glitch (if applicable):
n/a
#### My Minecraft username:
n0TaN00b473

#### What I was doing when the glitch occurred:
Spleef minigame

#### What happened:
When the opponent made me fall down a level at the TOP level, it said he won.

#### What was supposed to happen:
He was supposed to not win?

#### Any additional details that should be noted (pictures/videos of it happening, etc):
This was after Jason fixed the glitch of two people dying at the same time (nobody would win).

**Comment by JasonHorkles** [comment]
It probably didn't reset correctly as I am unable to reproduce it now. Please comment on this issue if you encounter it again.

**Comment by n0TaN00b473** [comment]
I happened again, i think it only happens with 3 players or something.

**Comment by n0TaN00b473** [comment]
*it

**Comment by JasonHorkles** [comment]
> *it

*you can edit messages btw*

**Comment by JasonHorkles** [comment]
Did this happen the first time you had 3 people playing or after it reset later?

**Comment by n0TaN00b473** [comment]
I don't know what you mean

**Comment by n0TaN00b473** [comment]
I'm actually not entirely sure that there was 3 people the first time

**Comment by JasonHorkles** [comment]
Did the problem happen when there were actually 3 people tho

**Comment by n0TaN00b473** [comment]
yes?

**Comment by n0TaN00b473** [comment]
except this time, there were 3 people at the top, and when somebody fell, it said someone at the top won

**Comment by n0TaN00b473** [comment]
...if that makes sense

**Comment by JasonHorkles** [comment]
3 people on the first layer of snow or on the very top of the game in the spectating area?

**Comment by n0TaN00b473** [comment]
Oh, sorry. The first layer of snow.

**Comment by n0TaN00b473** [comment]
Not spectating.

**Comment by n0TaN00b473** [comment]
i can try to record it next time, if that helps

**Comment by JasonHorkles** [comment]
OK so just to be clear: There were 3 people on the first layer of snow, 1 fell down a single layer, leaving 2 remaining at the first layer. Correct?
Yes that'd be very helpful.

**Comment by n0TaN00b473** [comment]
Yes, and then it said one of the 2 people remaining on the first layer one.

**Comment by n0TaN00b473** [comment]
This is not fixed, it happened again with me and GalaxyCat again. I knocked galaxy down one layer at the top layer and it said I won. I tried to record it but I couldn't, sorry.

**Comment by JasonHorkles** [comment]
A possible fix has been implemented.
