### ISSUE TITLE
[BUG] Hider continued glowing throughout the entire game, it said there was only one hider when there was two, and when the hider died they continued being a block

### ISSUE THREAD

**Issue by n0TaN00b473** [JasonHorkles/Silverstone#28]
#### Server this occurred in (in the player tab list):
main

#### World this occurred in (in the player tab list):
Minigames

#### The coordinates or a notable location at/near the glitch (if applicable):
Hide & Seek

#### My Minecraft username:
n0TaN00b473

#### What I was doing when the glitch occurred:
I was the seeker with 2 other people in hide and seek

#### What happened:
One of the hiders continued glowing the entire game, but the other hider didn't. It said there was only one hider, but there were two, and both were alive. Also, when one of the hiders died, (The one glowing) was still a block and was still glowing.

#### What was supposed to happen:
They weren't supposed to glow, there was supposed to be both the hider's names on the screen, and the one I killed should have been a seeker and not a block.

#### Any additional details that should be noted (pictures/videos of it happening, etc):
![2020-11-14_21 04 09](https://user-images.githubusercontent.com/69173157/99162739-303edd00-26be-11eb-8d7b-1bef12e7efd8.png)

**Comment by JasonHorkles** [comment]
Potentially fixed
