### ISSUE TITLE
[BUILDER] dash794

### ISSUE THREAD

**Issue by dash794** [JasonHorkles/Silverstone#29]
#### Am I re-submitting my application?

no
#### My Discord username and tag (optional, would only be used for better communication):

dash794 #6299
#### My Minecraft username:

dash794
#### My current rank (shown in tab):

Mod
#### Why I want to be a builder:

More plots
#### On a scale of 1-10, how good of a builder do I think I'd be (1 being terrible and 10 being fantastic)?

8
#### Do I feel like I'm worthy of being a builder?

yes
#### Do I swear I'll do my best to follow the server rules at all times?

_____yes
## My builds

![image](https://user-images.githubusercontent.com/68916558/99595687-27525200-29c3-11eb-8892-a2e7b8f7ef2f.png)
![image](https://user-images.githubusercontent.com/68916558/99595713-3507d780-29c3-11eb-9656-61b090fa2ded.png)
![image](https://user-images.githubusercontent.com/68916558/99595769-451fb700-29c3-11eb-92de-2d696c2be2f9.png)

**Comment by JasonHorkles** [comment]
The Builder rank is specifically designed for people who intend on building large-scale projects for the server. We have plans to expand the max amount of plots players can claim in the player shops, but that's not the main reason the Builder rank should be applied for.
