### ISSUE TITLE
[BUG] Free xp with sell sticks

### ISSUE THREAD

**Issue by AlbaAurDraconis** [JasonHorkles/Silverstone#32]
#### Server this occurred in (in the player tab list):

main
#### World this occurred in (in the player tab list):

main
#### The coordinates or a notable location at/near the glitch (if applicable):

n/a
#### My Minecraft username:

AlbaAurDraconis
#### What I was doing when the glitch occurred:

tried disenchanting a sell stick
#### What happened:

it worked and i got xp
#### What was supposed to happen:

Probably not suppoused to get free xp
#### Any additional details that should be noted (pictures/videos of it happening, etc):

n/a

**Comment by JasonHorkles** [comment]
Already brought up with plugin author, may or may not be solution in future
