### ISSUE TITLE
Sell stick's enchantment disappears when switching gamemodes

### ISSUE THREAD

**Issue by Acealation** [JasonHorkles/Silverstone#34]
#### Server this occurred in (in the player tab list):

Main
#### World this occurred in (in the player tab list):

Main
#### The coordinates or a notable location at/near the glitch (if applicable):

-4269, -2535
#### My Minecraft username:

Acealation
#### What I was doing when the glitch occurred:

Going to survival
#### What happened:

I switched to survival and it removed the enchantment from the sell stick

#### What was supposed to happen:

Not remove the enchant
#### Any additional details that should be noted (pictures/videos of it happening, etc):

![image](https://user-images.githubusercontent.com/78876410/107560664-dce40a00-6b9a-11eb-9c71-aced33de3bd3.png)

**Comment by JasonHorkles** [comment]
Will be fixed when the plots are reopened
