### ISSUE TITLE
[GRIEF REPORT]

### ISSUE THREAD

**Issue by n0TaN00b473** [JasonHorkles/Silverstone#37]
#### My MC username:
n0TaN00b473

#### What happened:
I had a villager house thing made of obsidian and I spent so long collecting obsidian, and I forgot to claim it, and now the walls have been torn apart, and I think I lost one of my villagers.

#### The coordinates at the location of the grief:
-8896 64 931

**Comment by JasonHorkles** [comment]
**thetomato33** has been successfully warned for griefing and the reported damage has been restored.
