### ISSUE TITLE
Killaura jail because of glitch

### ISSUE THREAD

**Issue by Error701** [JasonHorkles/Silverstone#42]
#### Server this occurred in (in the player tab list):

main server
#### World this occurred in (in the player tab list):

mainpvp server
#### The coordinates or a notable location at/near the glitch (if applicable):

Near the end portal
#### My Minecraft username:

Error701
#### What I was doing when the glitch occurred:

killing endermen with sweeping edge 3 and jumping rapidly for crits
#### What happened:

I got jailed for killaura
#### What was supposed to happen:

not getting jailed? I was just killing endermen
#### Any additional details that should be noted (pictures/videos of it happening, etc):

no

**Comment by JasonHorkles** [comment]
Lol mainpvp was discontinued ages ago
Anyways I'll forward this to the anti-cheat if I'm able to reproduce it

**Comment by JasonHorkles** [comment]
Can't reproduce, please provide video evidence if you can reproduce it again
