### ISSUE TITLE
Punishment Appeal

### ISSUE THREAD

**Issue by Error701** [JasonHorkles/Silverstone#45]
### My Minecraft username

Chilling_frost

### My current rank

Millionaire

### What I did to get punished

"griefing"

### Why I want my punishment to be lifted

I wasn't actually stealing his sword, I took it to enchant it to make it op as a gift but I had to get off and was too late.

### Will I ever repeat what I did to get punished?

no

### By checking this box I agree to never again do what I did to get punished. I also understand that future appeals may not be accepted if I am punished again.

- [x] I agree

**Comment by Error701** [comment]
Court has decreed him not guilty

**Comment by JasonHorkles** [comment]
The punishment has been reduced to 24 hours.

For future reference, do not take players' items without their permission for any reason.
The next griefing offense will be a permanent ban from the network.
