### ISSUE TITLE
End flying bug

### ISSUE THREAD

**Issue by SimpleTequila** [JasonHorkles/Silverstone#5]
#### Server this occurred in (in the player tab list):
Main server

#### World this occurred in (in the player tab list):
The end + Overworld

#### My Minecraft username:
SimpleTequila

#### What I was doing when the glitch occurred:
Fighting ender dragon

#### What happened:
I was able to fly in the end by already flying before entering the end portal.

#### What was supposed to happen:
I shouldn't have been able to fly whatsoever in the end

**Comment by JasonHorkles** [comment]
A fix has been implemented. Please reopen this issue if it still occurs.
