### ISSUE TITLE
[STAFF] Falcynn

### ISSUE THREAD

**Issue by sutariyatej** [JasonHorkles/Silverstone#6]
#### Am I re-submitting my application?
No

#### My Discord username and tag:
jet#3136

#### My Minecraft username:
Falcynn

#### My current rank (shown in tab):
default

#### My current time played on the server:
25 hours 22 minutes and 15 seconds

#### My current age (if you don't want this to be public DM it to me on Discord): 

20

#### Why I want to be a staff member:
I want to be a moderator on the server to help ensure the server continues running in an orderly manner that is welcoming to all players. I am online almost everyday, so during my time on, I want members to be able to notice me as someone who is friendly and available to help.

#### How often am I / will I be on the server?
Everyday for at least a few hours

#### On a scale of 1-10, how good of a staff member do I think I'd be (1 being terrible and 10 being fantastic)?
10

#### Do I feel like I'm worthy of being a staff member?
Yes, based on my years of moderating and running servers on Minecraft, I believe I am worthy. I would like to help ensure that this server continues growing while staying a nice, friendly community

#### Do I swear I'll do my best to enforce the server rules at all times?
Yes, I swear.

**Comment by JasonHorkles** [comment]
We will consider your request after you have read and accepted the rules in the Discord server.

**Comment by JasonHorkles** [comment]
We have decided to give you trial mod for 1 week and will evaluate your performance when it expires

**Comment by editid1** [comment]
hi
