### ISSUE TITLE
[BUG] instantly fall into void upon entering end dimension

### ISSUE THREAD

**Issue by ninjazyborg** [JasonHorkles/Silverstone#8]
#### Server this occurred in (in the player tab list):
main

#### World this occurred in (in the player tab list):
end

#### The coordinates at/near the glitch (if applicable):
N/A

#### My Minecraft username:
ninjazyborg

#### What I was doing when the glitch occurred:
entering the end

#### What happened:
the chunk appeared to not load and I proceeded to fall into the void and die

#### What was supposed to happen:
the chunk was supposed to load and I wasn't supposed to fall into the void and die

#### Any additional details that should be noted:
i'd like my stuff back lol
also this doesn't appear to happen every time

**Comment by slyfoxdiscord** [comment]
funny

**Comment by JasonHorkles** [comment]
A possible fix has been implemented. If you continue to have the problem please leave a comment on this issue.

**Comment by JasonHorkles** [comment]
A different method has been implemented and should hopefully work. Going to close this issue for now.

**Comment by ninjazyborg** [comment]
happened to dash794 just now

**Comment by JasonHorkles** [comment]
It'd really be nice if someone could get a video of it happening

**Comment by JasonHorkles** [comment]
Another possible fix has been implemented. I am unable to recreate the issue, however, so it's a bit harder to fix something I haven't seen.
